version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: scores_flask
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./Scores.txt:/app/Scores.txt
      - ./requirements.txt:/app/requirements.txt
    environment:
      - FLASK_APP=MainScores.py
      - FLASK_RUN_HOST=0.0.0.0
    command: python -m flask run